spring:
  main:
    banner-mode: off
server:
  port: 1306

db2parquet:
  number-of-concurrent-syncs: 1
  output-path: /dev/null # Replace
  encryption-key: ThisIsNotAKey # Replace
  query-template: 'SELECT *'  # Put query template here
  schema-name: test-schema
  namespace: com.marcolotz
  number-of-rows-to-fetch: 10 # Replace
  jdbc:
    url: jdbc:oracle:thin:@192.168.100.1:5521/mydbservice?oracle.net.httpsProxyHost=myproxy&oracle.net.httpsProxyPort=80  # Replace
    driver-class: oracle.jdbc.driver.OracleDriver
    username: no-user  # Replace
    password: no-password  # Replace
    output-type: parquet
    fetch-size-in-rows: 10000 # Number of rows requested to the DB on each fetch operation
    max-file-size-in-bytes: 1073741824 # 1 GB
