spring:
  main:
    banner-mode: off

db2parquet:
  number-of-concurrent-syncs: 1
  jdbc:
    url:
    driver-class:
    username:
    password:
    output-type: parquet
    fetch-size-in-rows: 10000 # Number of rows requested to the DB on each fetch operation
    max-file-size-in-bytes: 1073741824 # 1 GB
