spring:
  main:
    banner-mode: off
server:
  port: 1306

db2parquet:
  number-of-concurrent-syncs: 1
  jdbc:
    url: jdbc:h2:~/testdb  # Replace
    driver-class: oracle.jdbc.driver.OracleDriver
    username: no-user  # Replace
    password: no-password  # Replace
    output-type: parquet
    fetch-size-in-rows: 10000 # Number of rows requested to the DB on each fetch operation
    max-file-size-in-bytes: 1073741824 # 1 GB
