openapi: "3.0.0"
info:
  version: 1.0.0
  title: Db2Parquet API
  license:
    name: Apache v2
servers:
  - url: http://localhost.swagger.io
paths:
  /v1/trigger:
    put:
      summary: Starts an ingestion on the configured database
      operationId: ingest data
      tags:
        - trigger
      responses:
        '204':
          description: Ingestion triggered
        '503':
          description: Another ingestion is currently running
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string